name: ecosystem-autorelayer-interop

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ethereum-optimism/factory/.github/workflows/docker-build.yaml@8a71ef009f8cc2b5284da3ed7642e1fffb59b01e
    with:
      image_name: ecosystem-autorelayer-interop
      context: .
      dockerfile: Dockerfile
      target: autorelayer-interop
      platforms: linux/amd64
      gcp_project_id: ${{ vars.GCP_PROJECT_ID_OPLABS_TOOLS_ARTIFACTS }}
      gcp_registry: us-docker.pkg.dev/oplabs-tools-artifacts/oss
      extraTags: type=raw,value=latest
      build_args: |
        DOCKER_TARGET=autorelayer-interop
    permissions:
      contents: read
      id-token: write
      attestations: write
